trigger:
- main

# ================= AGENT CONFIG =================
pool:
  name: 'Default'   # or your custom agent pool name
  demands:
    - Agent.Name -equals agentAlex

variables:
  pythonVersion: '3.13'

# ================= STAGES =================
stages:

# ----------- DEV STAGE -----------
- stage: Dev
  displayName: "DEV Deployment"
  jobs:
  - job: DevJob
    displayName: "Run App in DEV"
    steps:
    - script: |
        echo "Running on Agent: $(Agent.Name)"
        echo "Operating System: $(Agent.OS)"
        python --version
        pip --version
      displayName: "Verify Agent & Python"

    - script: |
        pip install -r requirements.txt
        python app.py
      displayName: "Install Dependencies & Run App (DEV)"

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)
        artifact: drop
      displayName: "Publish Artifact"

# ----------- UAT STAGE -----------
- stage: UAT
  displayName: "UAT Deployment"
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - deployment: UATDeploy
    displayName: "Run App in UAT"
    environment: 'UAT'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - script: |
              echo "Running on Agent: $(Agent.Name)"
              pip install -r requirements.txt
              python app.py
            displayName: "Install Dependencies & Run App (UAT)"

# ----------- PROD STAGE -----------
- stage: Prod
  displayName: "PROD Deployment"
  dependsOn: UAT
  condition: succeeded()
  jobs:
  - deployment: ProdDeploy
    displayName: "Run App in PROD"
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - script: |
              echo "Running on Agent: $(Agent.Name)"
              pip install -r requirements.txt
              python app.py
            displayName: "Install Dependencies & Run App (PROD)"
